/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * 200 ok object
 */
@Schema(description = "200 ok object")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-18T15:18:58.117336-05:00[America/New_York]")
public class GetCharactersCharacterIdFatigueOk {
  @SerializedName("jump_fatigue_expire_date")
  private OffsetDateTime jumpFatigueExpireDate = null;

  @SerializedName("last_jump_date")
  private OffsetDateTime lastJumpDate = null;

  @SerializedName("last_update_date")
  private OffsetDateTime lastUpdateDate = null;

  public GetCharactersCharacterIdFatigueOk jumpFatigueExpireDate(OffsetDateTime jumpFatigueExpireDate) {
    this.jumpFatigueExpireDate = jumpFatigueExpireDate;
    return this;
  }

   /**
   * Character&#x27;s jump fatigue expiry
   * @return jumpFatigueExpireDate
  **/
  @Schema(description = "Character's jump fatigue expiry")
  public OffsetDateTime getJumpFatigueExpireDate() {
    return jumpFatigueExpireDate;
  }

  public void setJumpFatigueExpireDate(OffsetDateTime jumpFatigueExpireDate) {
    this.jumpFatigueExpireDate = jumpFatigueExpireDate;
  }

  public GetCharactersCharacterIdFatigueOk lastJumpDate(OffsetDateTime lastJumpDate) {
    this.lastJumpDate = lastJumpDate;
    return this;
  }

   /**
   * Character&#x27;s last jump activation
   * @return lastJumpDate
  **/
  @Schema(description = "Character's last jump activation")
  public OffsetDateTime getLastJumpDate() {
    return lastJumpDate;
  }

  public void setLastJumpDate(OffsetDateTime lastJumpDate) {
    this.lastJumpDate = lastJumpDate;
  }

  public GetCharactersCharacterIdFatigueOk lastUpdateDate(OffsetDateTime lastUpdateDate) {
    this.lastUpdateDate = lastUpdateDate;
    return this;
  }

   /**
   * Character&#x27;s last jump update
   * @return lastUpdateDate
  **/
  @Schema(description = "Character's last jump update")
  public OffsetDateTime getLastUpdateDate() {
    return lastUpdateDate;
  }

  public void setLastUpdateDate(OffsetDateTime lastUpdateDate) {
    this.lastUpdateDate = lastUpdateDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCharactersCharacterIdFatigueOk getCharactersCharacterIdFatigueOk = (GetCharactersCharacterIdFatigueOk) o;
    return Objects.equals(this.jumpFatigueExpireDate, getCharactersCharacterIdFatigueOk.jumpFatigueExpireDate) &&
        Objects.equals(this.lastJumpDate, getCharactersCharacterIdFatigueOk.lastJumpDate) &&
        Objects.equals(this.lastUpdateDate, getCharactersCharacterIdFatigueOk.lastUpdateDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jumpFatigueExpireDate, lastJumpDate, lastUpdateDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCharactersCharacterIdFatigueOk {\n");
    
    sb.append("    jumpFatigueExpireDate: ").append(toIndentedString(jumpFatigueExpireDate)).append("\n");
    sb.append("    lastJumpDate: ").append(toIndentedString(lastJumpDate)).append("\n");
    sb.append("    lastUpdateDate: ").append(toIndentedString(lastUpdateDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
