/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * 200 ok object
 */
@Schema(description = "200 ok object")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-18T15:18:58.117336-05:00[America/New_York]")
public class GetCorporationsCorporationIdShareholders200Ok {
  @SerializedName("share_count")
  private Long shareCount = null;

  @SerializedName("shareholder_id")
  private Integer shareholderId = null;

  /**
   * shareholder_type string
   */
  @JsonAdapter(ShareholderTypeEnum.Adapter.class)
  public enum ShareholderTypeEnum {
    CHARACTER("character"),
    CORPORATION("corporation");

    private String value;

    ShareholderTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ShareholderTypeEnum fromValue(String input) {
      for (ShareholderTypeEnum b : ShareholderTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ShareholderTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ShareholderTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ShareholderTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return ShareholderTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("shareholder_type")
  private ShareholderTypeEnum shareholderType = null;

  public GetCorporationsCorporationIdShareholders200Ok shareCount(Long shareCount) {
    this.shareCount = shareCount;
    return this;
  }

   /**
   * share_count integer
   * @return shareCount
  **/
  @Schema(required = true, description = "share_count integer")
  public Long getShareCount() {
    return shareCount;
  }

  public void setShareCount(Long shareCount) {
    this.shareCount = shareCount;
  }

  public GetCorporationsCorporationIdShareholders200Ok shareholderId(Integer shareholderId) {
    this.shareholderId = shareholderId;
    return this;
  }

   /**
   * shareholder_id integer
   * @return shareholderId
  **/
  @Schema(required = true, description = "shareholder_id integer")
  public Integer getShareholderId() {
    return shareholderId;
  }

  public void setShareholderId(Integer shareholderId) {
    this.shareholderId = shareholderId;
  }

  public GetCorporationsCorporationIdShareholders200Ok shareholderType(ShareholderTypeEnum shareholderType) {
    this.shareholderType = shareholderType;
    return this;
  }

   /**
   * shareholder_type string
   * @return shareholderType
  **/
  @Schema(required = true, description = "shareholder_type string")
  public ShareholderTypeEnum getShareholderType() {
    return shareholderType;
  }

  public void setShareholderType(ShareholderTypeEnum shareholderType) {
    this.shareholderType = shareholderType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCorporationsCorporationIdShareholders200Ok getCorporationsCorporationIdShareholders200Ok = (GetCorporationsCorporationIdShareholders200Ok) o;
    return Objects.equals(this.shareCount, getCorporationsCorporationIdShareholders200Ok.shareCount) &&
        Objects.equals(this.shareholderId, getCorporationsCorporationIdShareholders200Ok.shareholderId) &&
        Objects.equals(this.shareholderType, getCorporationsCorporationIdShareholders200Ok.shareholderType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shareCount, shareholderId, shareholderType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCorporationsCorporationIdShareholders200Ok {\n");
    
    sb.append("    shareCount: ").append(toIndentedString(shareCount)).append("\n");
    sb.append("    shareholderId: ").append(toIndentedString(shareholderId)).append("\n");
    sb.append("    shareholderType: ").append(toIndentedString(shareholderType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
