/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.GetFwLeaderboardsCharactersKills;
import io.swagger.client.model.GetFwLeaderboardsCharactersVictoryPoints;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * 200 ok object
 */
@Schema(description = "200 ok object")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-18T15:18:58.117336-05:00[America/New_York]")
public class GetFwLeaderboardsCharactersOk {
  @SerializedName("kills")
  private GetFwLeaderboardsCharactersKills kills = null;

  @SerializedName("victory_points")
  private GetFwLeaderboardsCharactersVictoryPoints victoryPoints = null;

  public GetFwLeaderboardsCharactersOk kills(GetFwLeaderboardsCharactersKills kills) {
    this.kills = kills;
    return this;
  }

   /**
   * Get kills
   * @return kills
  **/
  @Schema(required = true, description = "")
  public GetFwLeaderboardsCharactersKills getKills() {
    return kills;
  }

  public void setKills(GetFwLeaderboardsCharactersKills kills) {
    this.kills = kills;
  }

  public GetFwLeaderboardsCharactersOk victoryPoints(GetFwLeaderboardsCharactersVictoryPoints victoryPoints) {
    this.victoryPoints = victoryPoints;
    return this;
  }

   /**
   * Get victoryPoints
   * @return victoryPoints
  **/
  @Schema(required = true, description = "")
  public GetFwLeaderboardsCharactersVictoryPoints getVictoryPoints() {
    return victoryPoints;
  }

  public void setVictoryPoints(GetFwLeaderboardsCharactersVictoryPoints victoryPoints) {
    this.victoryPoints = victoryPoints;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFwLeaderboardsCharactersOk getFwLeaderboardsCharactersOk = (GetFwLeaderboardsCharactersOk) o;
    return Objects.equals(this.kills, getFwLeaderboardsCharactersOk.kills) &&
        Objects.equals(this.victoryPoints, getFwLeaderboardsCharactersOk.victoryPoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kills, victoryPoints);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFwLeaderboardsCharactersOk {\n");
    
    sb.append("    kills: ").append(toIndentedString(kills)).append("\n");
    sb.append("    victoryPoints: ").append(toIndentedString(victoryPoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
