/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * level object
 */
@Schema(description = "level object")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-18T15:18:58.117336-05:00[America/New_York]")
public class GetInsurancePricesLevel {
  @SerializedName("cost")
  private Float cost = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("payout")
  private Float payout = null;

  public GetInsurancePricesLevel cost(Float cost) {
    this.cost = cost;
    return this;
  }

   /**
   * cost number
   * @return cost
  **/
  @Schema(required = true, description = "cost number")
  public Float getCost() {
    return cost;
  }

  public void setCost(Float cost) {
    this.cost = cost;
  }

  public GetInsurancePricesLevel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Localized insurance level
   * @return name
  **/
  @Schema(required = true, description = "Localized insurance level")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GetInsurancePricesLevel payout(Float payout) {
    this.payout = payout;
    return this;
  }

   /**
   * payout number
   * @return payout
  **/
  @Schema(required = true, description = "payout number")
  public Float getPayout() {
    return payout;
  }

  public void setPayout(Float payout) {
    this.payout = payout;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetInsurancePricesLevel getInsurancePricesLevel = (GetInsurancePricesLevel) o;
    return Objects.equals(this.cost, getInsurancePricesLevel.cost) &&
        Objects.equals(this.name, getInsurancePricesLevel.name) &&
        Objects.equals(this.payout, getInsurancePricesLevel.payout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cost, name, payout);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetInsurancePricesLevel {\n");
    
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    payout: ").append(toIndentedString(payout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
