/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.GetUniverseAsteroidBeltsAsteroidBeltIdPosition;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * 200 ok object
 */
@Schema(description = "200 ok object")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-18T15:18:58.117336-05:00[America/New_York]")
public class GetUniverseAsteroidBeltsAsteroidBeltIdOk {
  @SerializedName("name")
  private String name = null;

  @SerializedName("position")
  private GetUniverseAsteroidBeltsAsteroidBeltIdPosition position = null;

  @SerializedName("system_id")
  private Integer systemId = null;

  public GetUniverseAsteroidBeltsAsteroidBeltIdOk name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name string
   * @return name
  **/
  @Schema(required = true, description = "name string")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GetUniverseAsteroidBeltsAsteroidBeltIdOk position(GetUniverseAsteroidBeltsAsteroidBeltIdPosition position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @Schema(required = true, description = "")
  public GetUniverseAsteroidBeltsAsteroidBeltIdPosition getPosition() {
    return position;
  }

  public void setPosition(GetUniverseAsteroidBeltsAsteroidBeltIdPosition position) {
    this.position = position;
  }

  public GetUniverseAsteroidBeltsAsteroidBeltIdOk systemId(Integer systemId) {
    this.systemId = systemId;
    return this;
  }

   /**
   * The solar system this asteroid belt is in
   * @return systemId
  **/
  @Schema(required = true, description = "The solar system this asteroid belt is in")
  public Integer getSystemId() {
    return systemId;
  }

  public void setSystemId(Integer systemId) {
    this.systemId = systemId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUniverseAsteroidBeltsAsteroidBeltIdOk getUniverseAsteroidBeltsAsteroidBeltIdOk = (GetUniverseAsteroidBeltsAsteroidBeltIdOk) o;
    return Objects.equals(this.name, getUniverseAsteroidBeltsAsteroidBeltIdOk.name) &&
        Objects.equals(this.position, getUniverseAsteroidBeltsAsteroidBeltIdOk.position) &&
        Objects.equals(this.systemId, getUniverseAsteroidBeltsAsteroidBeltIdOk.systemId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, position, systemId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUniverseAsteroidBeltsAsteroidBeltIdOk {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    systemId: ").append(toIndentedString(systemId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
