/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BadRequest;
import io.swagger.client.model.ErrorLimited;
import io.swagger.client.model.GatewayTimeout;
import io.swagger.client.model.GetAlliancesAllianceIdIconsNotFound;
import io.swagger.client.model.GetAlliancesAllianceIdIconsOk;
import io.swagger.client.model.GetAlliancesAllianceIdNotFound;
import io.swagger.client.model.GetAlliancesAllianceIdOk;
import io.swagger.client.model.InternalServerError;
import io.swagger.client.model.ServiceUnavailable;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AllianceApi
 */
@Ignore
public class AllianceApiTest {

    private final AllianceApi api = new AllianceApi();

    /**
     * List all alliances
     *
     * List all active player alliances  --- Alternate route: &#x60;/latest/alliances/&#x60;  Alternate route: &#x60;/legacy/alliances/&#x60;  Alternate route: &#x60;/v1/alliances/&#x60;  Alternate route: &#x60;/v2/alliances/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAlliancesTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<Integer> response = api.getAlliances(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get alliance information
     *
     * Public information about an alliance  --- Alternate route: &#x60;/latest/alliances/{alliance_id}/&#x60;  Alternate route: &#x60;/legacy/alliances/{alliance_id}/&#x60;  Alternate route: &#x60;/v3/alliances/{alliance_id}/&#x60;  Alternate route: &#x60;/v4/alliances/{alliance_id}/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAlliancesAllianceIdTest() throws Exception {
        Integer allianceId = null;
        String datasource = null;
        String ifNoneMatch = null;
        GetAlliancesAllianceIdOk response = api.getAlliancesAllianceId(allianceId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * List alliance&#x27;s corporations
     *
     * List all current member corporations of an alliance  --- Alternate route: &#x60;/latest/alliances/{alliance_id}/corporations/&#x60;  Alternate route: &#x60;/legacy/alliances/{alliance_id}/corporations/&#x60;  Alternate route: &#x60;/v1/alliances/{alliance_id}/corporations/&#x60;  Alternate route: &#x60;/v2/alliances/{alliance_id}/corporations/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAlliancesAllianceIdCorporationsTest() throws Exception {
        Integer allianceId = null;
        String datasource = null;
        String ifNoneMatch = null;
        List<Integer> response = api.getAlliancesAllianceIdCorporations(allianceId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get alliance icon
     *
     * Get the icon urls for a alliance  --- Alternate route: &#x60;/v2/alliances/{alliance_id}/icons/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAlliancesAllianceIdIconsTest() throws Exception {
        Integer allianceId = null;
        String datasource = null;
        String ifNoneMatch = null;
        GetAlliancesAllianceIdIconsOk response = api.getAlliancesAllianceIdIcons(allianceId, datasource, ifNoneMatch);

        // TODO: test validations
    }
}
