/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BadRequest;
import io.swagger.client.model.ErrorLimited;
import io.swagger.client.model.Forbidden;
import io.swagger.client.model.GatewayTimeout;
import io.swagger.client.model.GetCharactersCharacterIdAssets200Ok;
import io.swagger.client.model.GetCharactersCharacterIdAssetsNotFound;
import io.swagger.client.model.GetCorporationsCorporationIdAssets200Ok;
import io.swagger.client.model.InternalServerError;
import io.swagger.client.model.PostCharactersCharacterIdAssetsLocations200Ok;
import io.swagger.client.model.PostCharactersCharacterIdAssetsNames200Ok;
import io.swagger.client.model.PostCorporationsCorporationIdAssetsLocations200Ok;
import io.swagger.client.model.PostCorporationsCorporationIdAssetsLocationsNotFound;
import io.swagger.client.model.PostCorporationsCorporationIdAssetsNames200Ok;
import io.swagger.client.model.PostCorporationsCorporationIdAssetsNamesNotFound;
import io.swagger.client.model.ServiceUnavailable;
import io.swagger.client.model.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AssetsApi
 */
@Ignore
public class AssetsApiTest {

    private final AssetsApi api = new AssetsApi();

    /**
     * Get character assets
     *
     * Return a list of the characters assets  --- Alternate route: &#x60;/latest/characters/{character_id}/assets/&#x60;  Alternate route: &#x60;/v5/characters/{character_id}/assets/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdAssetsTest() throws Exception {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCharactersCharacterIdAssets200Ok> response = api.getCharactersCharacterIdAssets(characterId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * Get corporation assets
     *
     * Return a list of the corporation assets  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/assets/&#x60;  Alternate route: &#x60;/v5/corporations/{corporation_id}/assets/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdAssetsTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdAssets200Ok> response = api.getCorporationsCorporationIdAssets(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * Get character asset locations
     *
     * Return locations for a set of item ids, which you can get from character assets endpoint. Coordinates for items in hangars or stations are set to (0,0,0)  --- Alternate route: &#x60;/latest/characters/{character_id}/assets/locations/&#x60;  Alternate route: &#x60;/v2/characters/{character_id}/assets/locations/&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postCharactersCharacterIdAssetsLocationsTest() throws Exception {
        List<Long> body = null;
        Integer characterId = null;
        String datasource = null;
        String token = null;
        List<PostCharactersCharacterIdAssetsLocations200Ok> response = api.postCharactersCharacterIdAssetsLocations(body, characterId, datasource, token);

        // TODO: test validations
    }
    /**
     * Get character asset names
     *
     * Return names for a set of item ids, which you can get from character assets endpoint. Typically used for items that can customize names, like containers or ships.  --- Alternate route: &#x60;/latest/characters/{character_id}/assets/names/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/assets/names/&#x60;  Alternate route: &#x60;/v1/characters/{character_id}/assets/names/&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postCharactersCharacterIdAssetsNamesTest() throws Exception {
        List<Long> body = null;
        Integer characterId = null;
        String datasource = null;
        String token = null;
        List<PostCharactersCharacterIdAssetsNames200Ok> response = api.postCharactersCharacterIdAssetsNames(body, characterId, datasource, token);

        // TODO: test validations
    }
    /**
     * Get corporation asset locations
     *
     * Return locations for a set of item ids, which you can get from corporation assets endpoint. Coordinates for items in hangars or stations are set to (0,0,0)  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/assets/locations/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/assets/locations/&#x60;   --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postCorporationsCorporationIdAssetsLocationsTest() throws Exception {
        List<Long> body = null;
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        List<PostCorporationsCorporationIdAssetsLocations200Ok> response = api.postCorporationsCorporationIdAssetsLocations(body, corporationId, datasource, token);

        // TODO: test validations
    }
    /**
     * Get corporation asset names
     *
     * Return names for a set of item ids, which you can get from corporation assets endpoint. Only valid for items that can customize names, like containers or ships  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/assets/names/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/assets/names/&#x60;  Alternate route: &#x60;/v1/corporations/{corporation_id}/assets/names/&#x60;   --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postCorporationsCorporationIdAssetsNamesTest() throws Exception {
        List<Long> body = null;
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        List<PostCorporationsCorporationIdAssetsNames200Ok> response = api.postCorporationsCorporationIdAssetsNames(body, corporationId, datasource, token);

        // TODO: test validations
    }
}
