/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BadRequest;
import io.swagger.client.model.ErrorLimited;
import io.swagger.client.model.Forbidden;
import io.swagger.client.model.GatewayTimeout;
import io.swagger.client.model.GetCharactersCharacterIdCalendar200Ok;
import io.swagger.client.model.GetCharactersCharacterIdCalendarEventIdAttendees200Ok;
import io.swagger.client.model.GetCharactersCharacterIdCalendarEventIdAttendeesNotFound;
import io.swagger.client.model.GetCharactersCharacterIdCalendarEventIdNotFound;
import io.swagger.client.model.GetCharactersCharacterIdCalendarEventIdOk;
import io.swagger.client.model.InternalServerError;
import io.swagger.client.model.PutCharactersCharacterIdCalendarEventIdResponse;
import io.swagger.client.model.ServiceUnavailable;
import io.swagger.client.model.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CalendarApi
 */
@Ignore
public class CalendarApiTest {

    private final CalendarApi api = new CalendarApi();

    /**
     * List calendar event summaries
     *
     * Get 50 event summaries from the calendar. If no from_event ID is given, the resource will return the next 50 chronological event summaries from now. If a from_event ID is specified, it will return the next 50 chronological event summaries from after that event  --- Alternate route: &#x60;/latest/characters/{character_id}/calendar/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/calendar/&#x60;  Alternate route: &#x60;/v1/characters/{character_id}/calendar/&#x60;  Alternate route: &#x60;/v2/characters/{character_id}/calendar/&#x60;  --- This route is cached for up to 5 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdCalendarTest() throws Exception {
        Integer characterId = null;
        String datasource = null;
        Integer fromEvent = null;
        String ifNoneMatch = null;
        String token = null;
        List<GetCharactersCharacterIdCalendar200Ok> response = api.getCharactersCharacterIdCalendar(characterId, datasource, fromEvent, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Get an event
     *
     * Get all the information for a specific event  --- Alternate route: &#x60;/latest/characters/{character_id}/calendar/{event_id}/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/calendar/{event_id}/&#x60;  Alternate route: &#x60;/v3/characters/{character_id}/calendar/{event_id}/&#x60;  Alternate route: &#x60;/v4/characters/{character_id}/calendar/{event_id}/&#x60;  --- This route is cached for up to 5 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdCalendarEventIdTest() throws Exception {
        Integer characterId = null;
        Integer eventId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        GetCharactersCharacterIdCalendarEventIdOk response = api.getCharactersCharacterIdCalendarEventId(characterId, eventId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Get attendees
     *
     * Get all invited attendees for a given event  --- Alternate route: &#x60;/latest/characters/{character_id}/calendar/{event_id}/attendees/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/calendar/{event_id}/attendees/&#x60;  Alternate route: &#x60;/v1/characters/{character_id}/calendar/{event_id}/attendees/&#x60;  Alternate route: &#x60;/v2/characters/{character_id}/calendar/{event_id}/attendees/&#x60;  --- This route is cached for up to 600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdCalendarEventIdAttendeesTest() throws Exception {
        Integer characterId = null;
        Integer eventId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<GetCharactersCharacterIdCalendarEventIdAttendees200Ok> response = api.getCharactersCharacterIdCalendarEventIdAttendees(characterId, eventId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Respond to an event
     *
     * Set your response status to an event  --- Alternate route: &#x60;/latest/characters/{character_id}/calendar/{event_id}/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/calendar/{event_id}/&#x60;  Alternate route: &#x60;/v3/characters/{character_id}/calendar/{event_id}/&#x60;  Alternate route: &#x60;/v4/characters/{character_id}/calendar/{event_id}/&#x60;  --- This route is cached for up to 5 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void putCharactersCharacterIdCalendarEventIdTest() throws Exception {
        PutCharactersCharacterIdCalendarEventIdResponse body = null;
        Integer characterId = null;
        Integer eventId = null;
        String datasource = null;
        String token = null;
        api.putCharactersCharacterIdCalendarEventId(body, characterId, eventId, datasource, token);

        // TODO: test validations
    }
}
