/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BadRequest;
import io.swagger.client.model.ErrorLimited;
import io.swagger.client.model.Forbidden;
import io.swagger.client.model.GatewayTimeout;
import io.swagger.client.model.GetCorporationsCorporationIdAlliancehistory200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdBlueprints200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdContainersLogs200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdDivisionsOk;
import io.swagger.client.model.GetCorporationsCorporationIdFacilities200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdIconsNotFound;
import io.swagger.client.model.GetCorporationsCorporationIdIconsOk;
import io.swagger.client.model.GetCorporationsCorporationIdMedals200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdMedalsIssued200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdMembersTitles200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdMembertracking200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdNotFound;
import io.swagger.client.model.GetCorporationsCorporationIdOk;
import io.swagger.client.model.GetCorporationsCorporationIdRoles200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdRolesHistory200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdShareholders200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdStandings200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdStarbases200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdStarbasesStarbaseIdOk;
import io.swagger.client.model.GetCorporationsCorporationIdStructures200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdTitles200Ok;
import io.swagger.client.model.InternalServerError;
import io.swagger.client.model.ServiceUnavailable;
import io.swagger.client.model.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CorporationApi
 */
@Ignore
public class CorporationApiTest {

    private final CorporationApi api = new CorporationApi();

    /**
     * Get corporation information
     *
     * Public information about a corporation  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/&#x60;  Alternate route: &#x60;/v5/corporations/{corporation_id}/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        GetCorporationsCorporationIdOk response = api.getCorporationsCorporationId(corporationId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get alliance history
     *
     * Get a list of all the alliances a corporation has been a member of  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/alliancehistory/&#x60;  Alternate route: &#x60;/v3/corporations/{corporation_id}/alliancehistory/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdAlliancehistoryTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        List<GetCorporationsCorporationIdAlliancehistory200Ok> response = api.getCorporationsCorporationIdAlliancehistory(corporationId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get corporation blueprints
     *
     * Returns a list of blueprints the corporation owns  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/blueprints/&#x60;  Alternate route: &#x60;/v3/corporations/{corporation_id}/blueprints/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdBlueprintsTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdBlueprints200Ok> response = api.getCorporationsCorporationIdBlueprints(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * Get all corporation ALSC logs
     *
     * Returns logs recorded in the past seven days from all audit log secure containers (ALSC) owned by a given corporation  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/containers/logs/&#x60;  Alternate route: &#x60;/v3/corporations/{corporation_id}/containers/logs/&#x60;  --- This route is cached for up to 600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdContainersLogsTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdContainersLogs200Ok> response = api.getCorporationsCorporationIdContainersLogs(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * Get corporation divisions
     *
     * Return corporation hangar and wallet division names, only show if a division is not using the default name  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/divisions/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/divisions/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdDivisionsTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        GetCorporationsCorporationIdDivisionsOk response = api.getCorporationsCorporationIdDivisions(corporationId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Get corporation facilities
     *
     * Return a corporation&#x27;s facilities  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/facilities/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/facilities/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Factory_Manager 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdFacilitiesTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<GetCorporationsCorporationIdFacilities200Ok> response = api.getCorporationsCorporationIdFacilities(corporationId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Get corporation icon
     *
     * Get the icon urls for a corporation  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/icons/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/icons/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdIconsTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        GetCorporationsCorporationIdIconsOk response = api.getCorporationsCorporationIdIcons(corporationId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get corporation medals
     *
     * Returns a corporation&#x27;s medals  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/medals/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/medals/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMedalsTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdMedals200Ok> response = api.getCorporationsCorporationIdMedals(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * Get corporation issued medals
     *
     * Returns medals issued by a corporation  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/medals/issued/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/medals/issued/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMedalsIssuedTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdMedalsIssued200Ok> response = api.getCorporationsCorporationIdMedalsIssued(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * Get corporation members
     *
     * Return the current member list of a corporation, the token&#x27;s character need to be a member of the corporation.  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/members/&#x60;  Alternate route: &#x60;/v4/corporations/{corporation_id}/members/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMembersTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<Integer> response = api.getCorporationsCorporationIdMembers(corporationId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Get corporation member limit
     *
     * Return a corporation&#x27;s member limit, not including CEO himself  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/members/limit/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/members/limit/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMembersLimitTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        Integer response = api.getCorporationsCorporationIdMembersLimit(corporationId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Get corporation&#x27;s members&#x27; titles
     *
     * Returns a corporation&#x27;s members&#x27; titles  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/members/titles/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/members/titles/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMembersTitlesTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<GetCorporationsCorporationIdMembersTitles200Ok> response = api.getCorporationsCorporationIdMembersTitles(corporationId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Track corporation members
     *
     * Returns additional information about a corporation&#x27;s members which helps tracking their activities  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/membertracking/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/membertracking/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMembertrackingTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<GetCorporationsCorporationIdMembertracking200Ok> response = api.getCorporationsCorporationIdMembertracking(corporationId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Get corporation member roles
     *
     * Return the roles of all members if the character has the personnel manager role or any grantable role.  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/roles/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/roles/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdRolesTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<GetCorporationsCorporationIdRoles200Ok> response = api.getCorporationsCorporationIdRoles(corporationId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Get corporation member roles history
     *
     * Return how roles have changed for a coporation&#x27;s members, up to a month  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/roles/history/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/roles/history/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdRolesHistoryTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdRolesHistory200Ok> response = api.getCorporationsCorporationIdRolesHistory(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * Get corporation shareholders
     *
     * Return the current shareholders of a corporation.  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/shareholders/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/shareholders/&#x60;  Alternate route: &#x60;/v1/corporations/{corporation_id}/shareholders/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdShareholdersTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdShareholders200Ok> response = api.getCorporationsCorporationIdShareholders(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * Get corporation standings
     *
     * Return corporation standings from agents, NPC corporations, and factions  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/standings/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/standings/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdStandingsTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdStandings200Ok> response = api.getCorporationsCorporationIdStandings(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * Get corporation starbases (POSes)
     *
     * Returns list of corporation starbases (POSes)  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/starbases/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/starbases/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdStarbasesTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdStarbases200Ok> response = api.getCorporationsCorporationIdStarbases(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * Get starbase (POS) detail
     *
     * Returns various settings and fuels of a starbase (POS)  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/starbases/{starbase_id}/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/starbases/{starbase_id}/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdStarbasesStarbaseIdTest() throws Exception {
        Integer corporationId = null;
        Long starbaseId = null;
        Integer systemId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        GetCorporationsCorporationIdStarbasesStarbaseIdOk response = api.getCorporationsCorporationIdStarbasesStarbaseId(corporationId, starbaseId, systemId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Get corporation structures
     *
     * Get a list of corporation structures. This route&#x27;s version includes the changes to structures detailed in this blog: https://www.eveonline.com/article/upwell-2.0-structures-changes-coming-on-february-13th  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/structures/&#x60;  Alternate route: &#x60;/v4/corporations/{corporation_id}/structures/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Station_Manager 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdStructuresTest() throws Exception {
        Integer corporationId = null;
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdStructures200Ok> response = api.getCorporationsCorporationIdStructures(corporationId, acceptLanguage, datasource, ifNoneMatch, language, page, token);

        // TODO: test validations
    }
    /**
     * Get corporation titles
     *
     * Returns a corporation&#x27;s titles  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/titles/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/titles/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdTitlesTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<GetCorporationsCorporationIdTitles200Ok> response = api.getCorporationsCorporationIdTitles(corporationId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Get npc corporations
     *
     * Get a list of npc corporations  --- Alternate route: &#x60;/latest/corporations/npccorps/&#x60;  Alternate route: &#x60;/v2/corporations/npccorps/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsNpccorpsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<Integer> response = api.getCorporationsNpccorps(datasource, ifNoneMatch);

        // TODO: test validations
    }
}
