/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BadRequest;
import io.swagger.client.model.ErrorLimited;
import io.swagger.client.model.Forbidden;
import io.swagger.client.model.GatewayTimeout;
import io.swagger.client.model.GetCharactersCharacterIdFwStatsOk;
import io.swagger.client.model.GetCorporationsCorporationIdFwStatsOk;
import io.swagger.client.model.GetFwLeaderboardsCharactersOk;
import io.swagger.client.model.GetFwLeaderboardsCorporationsOk;
import io.swagger.client.model.GetFwLeaderboardsOk;
import io.swagger.client.model.GetFwStats200Ok;
import io.swagger.client.model.GetFwSystems200Ok;
import io.swagger.client.model.GetFwWars200Ok;
import io.swagger.client.model.InternalServerError;
import io.swagger.client.model.ServiceUnavailable;
import io.swagger.client.model.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for FactionWarfareApi
 */
@Ignore
public class FactionWarfareApiTest {

    private final FactionWarfareApi api = new FactionWarfareApi();

    /**
     * Overview of a character involved in faction warfare
     *
     * Statistical overview of a character involved in faction warfare  --- Alternate route: &#x60;/latest/characters/{character_id}/fw/stats/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fw/stats/&#x60;  Alternate route: &#x60;/v1/characters/{character_id}/fw/stats/&#x60;  Alternate route: &#x60;/v2/characters/{character_id}/fw/stats/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdFwStatsTest() throws Exception {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        GetCharactersCharacterIdFwStatsOk response = api.getCharactersCharacterIdFwStats(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Overview of a corporation involved in faction warfare
     *
     * Statistics about a corporation involved in faction warfare  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/fw/stats/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/fw/stats/&#x60;  Alternate route: &#x60;/v1/corporations/{corporation_id}/fw/stats/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/fw/stats/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdFwStatsTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        GetCorporationsCorporationIdFwStatsOk response = api.getCorporationsCorporationIdFwStats(corporationId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * List of the top factions in faction warfare
     *
     * Top 4 leaderboard of factions for kills and victory points separated by total, last week and yesterday  --- Alternate route: &#x60;/latest/fw/leaderboards/&#x60;  Alternate route: &#x60;/legacy/fw/leaderboards/&#x60;  Alternate route: &#x60;/v1/fw/leaderboards/&#x60;  Alternate route: &#x60;/v2/fw/leaderboards/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFwLeaderboardsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        GetFwLeaderboardsOk response = api.getFwLeaderboards(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * List of the top pilots in faction warfare
     *
     * Top 100 leaderboard of pilots for kills and victory points separated by total, last week and yesterday  --- Alternate route: &#x60;/latest/fw/leaderboards/characters/&#x60;  Alternate route: &#x60;/legacy/fw/leaderboards/characters/&#x60;  Alternate route: &#x60;/v1/fw/leaderboards/characters/&#x60;  Alternate route: &#x60;/v2/fw/leaderboards/characters/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFwLeaderboardsCharactersTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        GetFwLeaderboardsCharactersOk response = api.getFwLeaderboardsCharacters(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * List of the top corporations in faction warfare
     *
     * Top 10 leaderboard of corporations for kills and victory points separated by total, last week and yesterday  --- Alternate route: &#x60;/latest/fw/leaderboards/corporations/&#x60;  Alternate route: &#x60;/legacy/fw/leaderboards/corporations/&#x60;  Alternate route: &#x60;/v1/fw/leaderboards/corporations/&#x60;  Alternate route: &#x60;/v2/fw/leaderboards/corporations/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFwLeaderboardsCorporationsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        GetFwLeaderboardsCorporationsOk response = api.getFwLeaderboardsCorporations(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * An overview of statistics about factions involved in faction warfare
     *
     * Statistical overviews of factions involved in faction warfare  --- Alternate route: &#x60;/latest/fw/stats/&#x60;  Alternate route: &#x60;/legacy/fw/stats/&#x60;  Alternate route: &#x60;/v1/fw/stats/&#x60;  Alternate route: &#x60;/v2/fw/stats/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFwStatsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<GetFwStats200Ok> response = api.getFwStats(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Ownership of faction warfare systems
     *
     * An overview of the current ownership of faction warfare solar systems  --- Alternate route: &#x60;/latest/fw/systems/&#x60;  Alternate route: &#x60;/legacy/fw/systems/&#x60;  Alternate route: &#x60;/v2/fw/systems/&#x60;  Alternate route: &#x60;/v3/fw/systems/&#x60;  --- This route is cached for up to 1800 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFwSystemsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<GetFwSystems200Ok> response = api.getFwSystems(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Data about which NPC factions are at war
     *
     * Data about which NPC factions are at war  --- Alternate route: &#x60;/latest/fw/wars/&#x60;  Alternate route: &#x60;/legacy/fw/wars/&#x60;  Alternate route: &#x60;/v1/fw/wars/&#x60;  Alternate route: &#x60;/v2/fw/wars/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFwWarsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<GetFwWars200Ok> response = api.getFwWars(datasource, ifNoneMatch);

        // TODO: test validations
    }
}
