/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BadRequest;
import io.swagger.client.model.ErrorLimited;
import io.swagger.client.model.Forbidden;
import io.swagger.client.model.GatewayTimeout;
import io.swagger.client.model.GetCharactersCharacterIdLoyaltyPoints200Ok;
import io.swagger.client.model.GetLoyaltyStoresCorporationIdOffers200Ok;
import io.swagger.client.model.GetLoyaltyStoresCorporationIdOffersNotFound;
import io.swagger.client.model.InternalServerError;
import io.swagger.client.model.ServiceUnavailable;
import io.swagger.client.model.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for LoyaltyApi
 */
@Ignore
public class LoyaltyApiTest {

    private final LoyaltyApi api = new LoyaltyApi();

    /**
     * Get loyalty points
     *
     * Return a list of loyalty points for all corporations the character has worked for  --- Alternate route: &#x60;/latest/characters/{character_id}/loyalty/points/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/loyalty/points/&#x60;  Alternate route: &#x60;/v1/characters/{character_id}/loyalty/points/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdLoyaltyPointsTest() throws Exception {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<GetCharactersCharacterIdLoyaltyPoints200Ok> response = api.getCharactersCharacterIdLoyaltyPoints(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * List loyalty store offers
     *
     * Return a list of offers from a specific corporation&#x27;s loyalty store  --- Alternate route: &#x60;/latest/loyalty/stores/{corporation_id}/offers/&#x60;  Alternate route: &#x60;/legacy/loyalty/stores/{corporation_id}/offers/&#x60;  Alternate route: &#x60;/v1/loyalty/stores/{corporation_id}/offers/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getLoyaltyStoresCorporationIdOffersTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        List<GetLoyaltyStoresCorporationIdOffers200Ok> response = api.getLoyaltyStoresCorporationIdOffers(corporationId, datasource, ifNoneMatch);

        // TODO: test validations
    }
}
