/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BadRequest;
import io.swagger.client.model.ErrorLimited;
import io.swagger.client.model.Forbidden;
import io.swagger.client.model.GatewayTimeout;
import io.swagger.client.model.GetCharactersCharacterIdOrders200Ok;
import io.swagger.client.model.GetCharactersCharacterIdOrdersHistory200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdOrders200Ok;
import io.swagger.client.model.GetCorporationsCorporationIdOrdersHistory200Ok;
import io.swagger.client.model.GetMarketsGroupsMarketGroupIdNotFound;
import io.swagger.client.model.GetMarketsGroupsMarketGroupIdOk;
import io.swagger.client.model.GetMarketsPrices200Ok;
import io.swagger.client.model.GetMarketsRegionIdHistory200Ok;
import io.swagger.client.model.GetMarketsRegionIdHistoryError520;
import io.swagger.client.model.GetMarketsRegionIdHistoryNotFound;
import io.swagger.client.model.GetMarketsRegionIdHistoryUnprocessableEntity;
import io.swagger.client.model.GetMarketsRegionIdOrders200Ok;
import io.swagger.client.model.GetMarketsRegionIdOrdersNotFound;
import io.swagger.client.model.GetMarketsRegionIdOrdersUnprocessableEntity;
import io.swagger.client.model.GetMarketsStructuresStructureId200Ok;
import io.swagger.client.model.InternalServerError;
import io.swagger.client.model.ServiceUnavailable;
import io.swagger.client.model.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for MarketApi
 */
@Ignore
public class MarketApiTest {

    private final MarketApi api = new MarketApi();

    /**
     * List open orders from a character
     *
     * List open market orders placed by a character  --- Alternate route: &#x60;/latest/characters/{character_id}/orders/&#x60;  Alternate route: &#x60;/v2/characters/{character_id}/orders/&#x60;  --- This route is cached for up to 1200 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdOrdersTest() throws Exception {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<GetCharactersCharacterIdOrders200Ok> response = api.getCharactersCharacterIdOrders(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * List historical orders by a character
     *
     * List cancelled and expired market orders placed by a character up to 90 days in the past.  --- Alternate route: &#x60;/latest/characters/{character_id}/orders/history/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/orders/history/&#x60;  Alternate route: &#x60;/v1/characters/{character_id}/orders/history/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdOrdersHistoryTest() throws Exception {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCharactersCharacterIdOrdersHistory200Ok> response = api.getCharactersCharacterIdOrdersHistory(characterId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * List open orders from a corporation
     *
     * List open market orders placed on behalf of a corporation  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/orders/&#x60;  Alternate route: &#x60;/v3/corporations/{corporation_id}/orders/&#x60;  --- This route is cached for up to 1200 seconds  --- Requires one of the following EVE corporation role(s): Accountant, Trader 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdOrdersTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdOrders200Ok> response = api.getCorporationsCorporationIdOrders(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * List historical orders from a corporation
     *
     * List cancelled and expired market orders placed on behalf of a corporation up to 90 days in the past.  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/orders/history/&#x60;  Alternate route: &#x60;/v2/corporations/{corporation_id}/orders/history/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Accountant, Trader 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdOrdersHistoryTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdOrdersHistory200Ok> response = api.getCorporationsCorporationIdOrdersHistory(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * Get item groups
     *
     * Get a list of item groups  --- Alternate route: &#x60;/latest/markets/groups/&#x60;  Alternate route: &#x60;/legacy/markets/groups/&#x60;  Alternate route: &#x60;/v1/markets/groups/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMarketsGroupsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<Integer> response = api.getMarketsGroups(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get item group information
     *
     * Get information on an item group  --- Alternate route: &#x60;/latest/markets/groups/{market_group_id}/&#x60;  Alternate route: &#x60;/legacy/markets/groups/{market_group_id}/&#x60;  Alternate route: &#x60;/v1/markets/groups/{market_group_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMarketsGroupsMarketGroupIdTest() throws Exception {
        Integer marketGroupId = null;
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        GetMarketsGroupsMarketGroupIdOk response = api.getMarketsGroupsMarketGroupId(marketGroupId, acceptLanguage, datasource, ifNoneMatch, language);

        // TODO: test validations
    }
    /**
     * List market prices
     *
     * Return a list of prices  --- Alternate route: &#x60;/latest/markets/prices/&#x60;  Alternate route: &#x60;/legacy/markets/prices/&#x60;  Alternate route: &#x60;/v1/markets/prices/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMarketsPricesTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<GetMarketsPrices200Ok> response = api.getMarketsPrices(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * List historical market statistics in a region
     *
     * Return a list of historical market statistics for the specified type in a region  --- Alternate route: &#x60;/latest/markets/{region_id}/history/&#x60;  Alternate route: &#x60;/legacy/markets/{region_id}/history/&#x60;  Alternate route: &#x60;/v1/markets/{region_id}/history/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMarketsRegionIdHistoryTest() throws Exception {
        Integer regionId = null;
        Integer typeId = null;
        String datasource = null;
        String ifNoneMatch = null;
        List<GetMarketsRegionIdHistory200Ok> response = api.getMarketsRegionIdHistory(regionId, typeId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * List orders in a region
     *
     * Return a list of orders in a region  --- Alternate route: &#x60;/latest/markets/{region_id}/orders/&#x60;  Alternate route: &#x60;/legacy/markets/{region_id}/orders/&#x60;  Alternate route: &#x60;/v1/markets/{region_id}/orders/&#x60;  --- This route is cached for up to 300 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMarketsRegionIdOrdersTest() throws Exception {
        String orderType = null;
        Integer regionId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        Integer typeId = null;
        List<GetMarketsRegionIdOrders200Ok> response = api.getMarketsRegionIdOrders(orderType, regionId, datasource, ifNoneMatch, page, typeId);

        // TODO: test validations
    }
    /**
     * List type IDs relevant to a market
     *
     * Return a list of type IDs that have active orders in the region, for efficient market indexing.  --- Alternate route: &#x60;/latest/markets/{region_id}/types/&#x60;  Alternate route: &#x60;/legacy/markets/{region_id}/types/&#x60;  Alternate route: &#x60;/v1/markets/{region_id}/types/&#x60;  --- This route is cached for up to 600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMarketsRegionIdTypesTest() throws Exception {
        Integer regionId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        List<Integer> response = api.getMarketsRegionIdTypes(regionId, datasource, ifNoneMatch, page);

        // TODO: test validations
    }
    /**
     * List orders in a structure
     *
     * Return all orders in a structure  --- Alternate route: &#x60;/latest/markets/structures/{structure_id}/&#x60;  Alternate route: &#x60;/legacy/markets/structures/{structure_id}/&#x60;  Alternate route: &#x60;/v1/markets/structures/{structure_id}/&#x60;  --- This route is cached for up to 300 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMarketsStructuresStructureIdTest() throws Exception {
        Long structureId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetMarketsStructuresStructureId200Ok> response = api.getMarketsStructuresStructureId(structureId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
}
