/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BadRequest;
import io.swagger.client.model.ErrorLimited;
import io.swagger.client.model.Forbidden;
import io.swagger.client.model.GatewayTimeout;
import io.swagger.client.model.GetCharactersCharacterIdPlanets200Ok;
import io.swagger.client.model.GetCharactersCharacterIdPlanetsPlanetIdNotFound;
import io.swagger.client.model.GetCharactersCharacterIdPlanetsPlanetIdOk;
import io.swagger.client.model.GetCorporationsCorporationIdCustomsOffices200Ok;
import io.swagger.client.model.GetUniverseSchematicsSchematicIdNotFound;
import io.swagger.client.model.GetUniverseSchematicsSchematicIdOk;
import io.swagger.client.model.InternalServerError;
import io.swagger.client.model.ServiceUnavailable;
import io.swagger.client.model.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for PlanetaryInteractionApi
 */
@Ignore
public class PlanetaryInteractionApiTest {

    private final PlanetaryInteractionApi api = new PlanetaryInteractionApi();

    /**
     * Get colonies
     *
     * Returns a list of all planetary colonies owned by a character.  --- Alternate route: &#x60;/latest/characters/{character_id}/planets/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/planets/&#x60;  Alternate route: &#x60;/v1/characters/{character_id}/planets/&#x60;  --- This route is cached for up to 600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdPlanetsTest() throws Exception {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<GetCharactersCharacterIdPlanets200Ok> response = api.getCharactersCharacterIdPlanets(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Get colony layout
     *
     * Returns full details on the layout of a single planetary colony, including links, pins and routes. Note: Planetary information is only recalculated when the colony is viewed through the client. Information will not update until this criteria is met.  --- Alternate route: &#x60;/latest/characters/{character_id}/planets/{planet_id}/&#x60;  Alternate route: &#x60;/v3/characters/{character_id}/planets/{planet_id}/&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdPlanetsPlanetIdTest() throws Exception {
        Integer characterId = null;
        Integer planetId = null;
        String datasource = null;
        String token = null;
        GetCharactersCharacterIdPlanetsPlanetIdOk response = api.getCharactersCharacterIdPlanetsPlanetId(characterId, planetId, datasource, token);

        // TODO: test validations
    }
    /**
     * List corporation customs offices
     *
     * List customs offices owned by a corporation  --- Alternate route: &#x60;/latest/corporations/{corporation_id}/customs_offices/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/customs_offices/&#x60;  Alternate route: &#x60;/v1/corporations/{corporation_id}/customs_offices/&#x60;  --- This route is cached for up to 3600 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdCustomsOfficesTest() throws Exception {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<GetCorporationsCorporationIdCustomsOffices200Ok> response = api.getCorporationsCorporationIdCustomsOffices(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    /**
     * Get schematic information
     *
     * Get information on a planetary factory schematic  --- Alternate route: &#x60;/latest/universe/schematics/{schematic_id}/&#x60;  Alternate route: &#x60;/legacy/universe/schematics/{schematic_id}/&#x60;  Alternate route: &#x60;/v1/universe/schematics/{schematic_id}/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseSchematicsSchematicIdTest() throws Exception {
        Integer schematicId = null;
        String datasource = null;
        String ifNoneMatch = null;
        GetUniverseSchematicsSchematicIdOk response = api.getUniverseSchematicsSchematicId(schematicId, datasource, ifNoneMatch);

        // TODO: test validations
    }
}
