/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BadRequest;
import io.swagger.client.model.ErrorLimited;
import io.swagger.client.model.Forbidden;
import io.swagger.client.model.GatewayTimeout;
import io.swagger.client.model.GetUniverseAncestries200Ok;
import io.swagger.client.model.GetUniverseAsteroidBeltsAsteroidBeltIdNotFound;
import io.swagger.client.model.GetUniverseAsteroidBeltsAsteroidBeltIdOk;
import io.swagger.client.model.GetUniverseBloodlines200Ok;
import io.swagger.client.model.GetUniverseCategoriesCategoryIdNotFound;
import io.swagger.client.model.GetUniverseCategoriesCategoryIdOk;
import io.swagger.client.model.GetUniverseConstellationsConstellationIdNotFound;
import io.swagger.client.model.GetUniverseConstellationsConstellationIdOk;
import io.swagger.client.model.GetUniverseFactions200Ok;
import io.swagger.client.model.GetUniverseGraphicsGraphicIdNotFound;
import io.swagger.client.model.GetUniverseGraphicsGraphicIdOk;
import io.swagger.client.model.GetUniverseGroupsGroupIdNotFound;
import io.swagger.client.model.GetUniverseGroupsGroupIdOk;
import io.swagger.client.model.GetUniverseMoonsMoonIdNotFound;
import io.swagger.client.model.GetUniverseMoonsMoonIdOk;
import io.swagger.client.model.GetUniversePlanetsPlanetIdNotFound;
import io.swagger.client.model.GetUniversePlanetsPlanetIdOk;
import io.swagger.client.model.GetUniverseRaces200Ok;
import io.swagger.client.model.GetUniverseRegionsRegionIdNotFound;
import io.swagger.client.model.GetUniverseRegionsRegionIdOk;
import io.swagger.client.model.GetUniverseStargatesStargateIdNotFound;
import io.swagger.client.model.GetUniverseStargatesStargateIdOk;
import io.swagger.client.model.GetUniverseStarsStarIdOk;
import io.swagger.client.model.GetUniverseStationsStationIdNotFound;
import io.swagger.client.model.GetUniverseStationsStationIdOk;
import io.swagger.client.model.GetUniverseStructuresStructureIdNotFound;
import io.swagger.client.model.GetUniverseStructuresStructureIdOk;
import io.swagger.client.model.GetUniverseSystemJumps200Ok;
import io.swagger.client.model.GetUniverseSystemKills200Ok;
import io.swagger.client.model.GetUniverseSystemsSystemIdNotFound;
import io.swagger.client.model.GetUniverseSystemsSystemIdOk;
import io.swagger.client.model.GetUniverseTypesTypeIdNotFound;
import io.swagger.client.model.GetUniverseTypesTypeIdOk;
import io.swagger.client.model.InternalServerError;
import io.swagger.client.model.PostUniverseIdsOk;
import io.swagger.client.model.PostUniverseNames200Ok;
import io.swagger.client.model.PostUniverseNamesNotFound;
import io.swagger.client.model.ServiceUnavailable;
import io.swagger.client.model.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UniverseApi
 */
@Ignore
public class UniverseApiTest {

    private final UniverseApi api = new UniverseApi();

    /**
     * Get ancestries
     *
     * Get all character ancestries  --- Alternate route: &#x60;/v2/universe/ancestries/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseAncestriesTest() throws Exception {
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        List<GetUniverseAncestries200Ok> response = api.getUniverseAncestries(acceptLanguage, datasource, ifNoneMatch, language);

        // TODO: test validations
    }
    /**
     * Get asteroid belt information
     *
     * Get information on an asteroid belt  --- Alternate route: &#x60;/v2/universe/asteroid_belts/{asteroid_belt_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseAsteroidBeltsAsteroidBeltIdTest() throws Exception {
        Integer asteroidBeltId = null;
        String datasource = null;
        String ifNoneMatch = null;
        GetUniverseAsteroidBeltsAsteroidBeltIdOk response = api.getUniverseAsteroidBeltsAsteroidBeltId(asteroidBeltId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get bloodlines
     *
     * Get a list of bloodlines  --- Alternate route: &#x60;/v2/universe/bloodlines/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseBloodlinesTest() throws Exception {
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        List<GetUniverseBloodlines200Ok> response = api.getUniverseBloodlines(acceptLanguage, datasource, ifNoneMatch, language);

        // TODO: test validations
    }
    /**
     * Get item categories
     *
     * Get a list of item categories  --- Alternate route: &#x60;/v2/universe/categories/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseCategoriesTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<Integer> response = api.getUniverseCategories(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get item category information
     *
     * Get information of an item category  --- Alternate route: &#x60;/v2/universe/categories/{category_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseCategoriesCategoryIdTest() throws Exception {
        Integer categoryId = null;
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        GetUniverseCategoriesCategoryIdOk response = api.getUniverseCategoriesCategoryId(categoryId, acceptLanguage, datasource, ifNoneMatch, language);

        // TODO: test validations
    }
    /**
     * Get constellations
     *
     * Get a list of constellations  --- Alternate route: &#x60;/v2/universe/constellations/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseConstellationsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<Integer> response = api.getUniverseConstellations(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get constellation information
     *
     * Get information on a constellation  --- Alternate route: &#x60;/v2/universe/constellations/{constellation_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseConstellationsConstellationIdTest() throws Exception {
        Integer constellationId = null;
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        GetUniverseConstellationsConstellationIdOk response = api.getUniverseConstellationsConstellationId(constellationId, acceptLanguage, datasource, ifNoneMatch, language);

        // TODO: test validations
    }
    /**
     * Get factions
     *
     * Get a list of factions  --- Alternate route: &#x60;/latest/universe/factions/&#x60;  Alternate route: &#x60;/v2/universe/factions/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseFactionsTest() throws Exception {
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        List<GetUniverseFactions200Ok> response = api.getUniverseFactions(acceptLanguage, datasource, ifNoneMatch, language);

        // TODO: test validations
    }
    /**
     * Get graphics
     *
     * Get a list of graphics  --- Alternate route: &#x60;/v2/universe/graphics/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseGraphicsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<Integer> response = api.getUniverseGraphics(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get graphic information
     *
     * Get information on a graphic  --- Alternate route: &#x60;/latest/universe/graphics/{graphic_id}/&#x60;  Alternate route: &#x60;/legacy/universe/graphics/{graphic_id}/&#x60;  Alternate route: &#x60;/v1/universe/graphics/{graphic_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseGraphicsGraphicIdTest() throws Exception {
        Integer graphicId = null;
        String datasource = null;
        String ifNoneMatch = null;
        GetUniverseGraphicsGraphicIdOk response = api.getUniverseGraphicsGraphicId(graphicId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get item groups
     *
     * Get a list of item groups  --- Alternate route: &#x60;/v2/universe/groups/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseGroupsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        List<Integer> response = api.getUniverseGroups(datasource, ifNoneMatch, page);

        // TODO: test validations
    }
    /**
     * Get item group information
     *
     * Get information on an item group  --- Alternate route: &#x60;/latest/universe/groups/{group_id}/&#x60;  Alternate route: &#x60;/legacy/universe/groups/{group_id}/&#x60;  Alternate route: &#x60;/v1/universe/groups/{group_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseGroupsGroupIdTest() throws Exception {
        Integer groupId = null;
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        GetUniverseGroupsGroupIdOk response = api.getUniverseGroupsGroupId(groupId, acceptLanguage, datasource, ifNoneMatch, language);

        // TODO: test validations
    }
    /**
     * Get moon information
     *
     * Get information on a moon  --- Alternate route: &#x60;/v2/universe/moons/{moon_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseMoonsMoonIdTest() throws Exception {
        Integer moonId = null;
        String datasource = null;
        String ifNoneMatch = null;
        GetUniverseMoonsMoonIdOk response = api.getUniverseMoonsMoonId(moonId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get planet information
     *
     * Get information on a planet  --- Alternate route: &#x60;/v2/universe/planets/{planet_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniversePlanetsPlanetIdTest() throws Exception {
        Integer planetId = null;
        String datasource = null;
        String ifNoneMatch = null;
        GetUniversePlanetsPlanetIdOk response = api.getUniversePlanetsPlanetId(planetId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get character races
     *
     * Get a list of character races  --- Alternate route: &#x60;/latest/universe/races/&#x60;  Alternate route: &#x60;/legacy/universe/races/&#x60;  Alternate route: &#x60;/v1/universe/races/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseRacesTest() throws Exception {
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        List<GetUniverseRaces200Ok> response = api.getUniverseRaces(acceptLanguage, datasource, ifNoneMatch, language);

        // TODO: test validations
    }
    /**
     * Get regions
     *
     * Get a list of regions  --- Alternate route: &#x60;/v2/universe/regions/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseRegionsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<Integer> response = api.getUniverseRegions(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get region information
     *
     * Get information on a region  --- Alternate route: &#x60;/v2/universe/regions/{region_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseRegionsRegionIdTest() throws Exception {
        Integer regionId = null;
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        GetUniverseRegionsRegionIdOk response = api.getUniverseRegionsRegionId(regionId, acceptLanguage, datasource, ifNoneMatch, language);

        // TODO: test validations
    }
    /**
     * Get stargate information
     *
     * Get information on a stargate  --- Alternate route: &#x60;/v2/universe/stargates/{stargate_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseStargatesStargateIdTest() throws Exception {
        Integer stargateId = null;
        String datasource = null;
        String ifNoneMatch = null;
        GetUniverseStargatesStargateIdOk response = api.getUniverseStargatesStargateId(stargateId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get star information
     *
     * Get information on a star  --- Alternate route: &#x60;/v2/universe/stars/{star_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseStarsStarIdTest() throws Exception {
        Integer starId = null;
        String datasource = null;
        String ifNoneMatch = null;
        GetUniverseStarsStarIdOk response = api.getUniverseStarsStarId(starId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get station information
     *
     * Get information on a station  --- Alternate route: &#x60;/latest/universe/stations/{station_id}/&#x60;  Alternate route: &#x60;/v2/universe/stations/{station_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseStationsStationIdTest() throws Exception {
        Integer stationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        GetUniverseStationsStationIdOk response = api.getUniverseStationsStationId(stationId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * List all public structures
     *
     * List all public structures  --- Alternate route: &#x60;/latest/universe/structures/&#x60;  Alternate route: &#x60;/legacy/universe/structures/&#x60;  Alternate route: &#x60;/v1/universe/structures/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseStructuresTest() throws Exception {
        String datasource = null;
        String filter = null;
        String ifNoneMatch = null;
        List<Long> response = api.getUniverseStructures(datasource, filter, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get structure information
     *
     * Returns information on requested structure if you are on the ACL. Otherwise, returns \&quot;Forbidden\&quot; for all inputs.  --- Alternate route: &#x60;/v3/universe/structures/{structure_id}/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseStructuresStructureIdTest() throws Exception {
        Long structureId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        GetUniverseStructuresStructureIdOk response = api.getUniverseStructuresStructureId(structureId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    /**
     * Get system jumps
     *
     * Get the number of jumps in solar systems within the last hour ending at the timestamp of the Last-Modified header, excluding wormhole space. Only systems with jumps will be listed  --- Alternate route: &#x60;/v2/universe/system_jumps/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseSystemJumpsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<GetUniverseSystemJumps200Ok> response = api.getUniverseSystemJumps(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get system kills
     *
     * Get the number of ship, pod and NPC kills per solar system within the last hour ending at the timestamp of the Last-Modified header, excluding wormhole space. Only systems with kills will be listed  --- Alternate route: &#x60;/v3/universe/system_kills/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseSystemKillsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<GetUniverseSystemKills200Ok> response = api.getUniverseSystemKills(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get solar systems
     *
     * Get a list of solar systems  --- Alternate route: &#x60;/latest/universe/systems/&#x60;  Alternate route: &#x60;/legacy/universe/systems/&#x60;  Alternate route: &#x60;/v1/universe/systems/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseSystemsTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        List<Integer> response = api.getUniverseSystems(datasource, ifNoneMatch);

        // TODO: test validations
    }
    /**
     * Get solar system information
     *
     * Get information on a solar system.  --- Alternate route: &#x60;/latest/universe/systems/{system_id}/&#x60;  Alternate route: &#x60;/v4/universe/systems/{system_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseSystemsSystemIdTest() throws Exception {
        Integer systemId = null;
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        GetUniverseSystemsSystemIdOk response = api.getUniverseSystemsSystemId(systemId, acceptLanguage, datasource, ifNoneMatch, language);

        // TODO: test validations
    }
    /**
     * Get types
     *
     * Get a list of type ids  --- Alternate route: &#x60;/v2/universe/types/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseTypesTest() throws Exception {
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        List<Integer> response = api.getUniverseTypes(datasource, ifNoneMatch, page);

        // TODO: test validations
    }
    /**
     * Get type information
     *
     * Get information on a type  --- Alternate route: &#x60;/latest/universe/types/{type_id}/&#x60;  Alternate route: &#x60;/v3/universe/types/{type_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUniverseTypesTypeIdTest() throws Exception {
        Integer typeId = null;
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        GetUniverseTypesTypeIdOk response = api.getUniverseTypesTypeId(typeId, acceptLanguage, datasource, ifNoneMatch, language);

        // TODO: test validations
    }
    /**
     * Bulk names to IDs
     *
     * Resolve a set of names to IDs in the following categories: agents, alliances, characters, constellations, corporations factions, inventory_types, regions, stations, and systems. Only exact matches will be returned. All names searched for are cached for 12 hours  --- Alternate route: &#x60;/latest/universe/ids/&#x60;  Alternate route: &#x60;/legacy/universe/ids/&#x60;  Alternate route: &#x60;/v1/universe/ids/&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postUniverseIdsTest() throws Exception {
        List<String> body = null;
        String acceptLanguage = null;
        String datasource = null;
        String language = null;
        PostUniverseIdsOk response = api.postUniverseIds(body, acceptLanguage, datasource, language);

        // TODO: test validations
    }
    /**
     * Get names and categories for a set of IDs
     *
     * Resolve a set of IDs to names and categories. Supported ID&#x27;s for resolving are: Characters, Corporations, Alliances, Stations, Solar Systems, Constellations, Regions, Types, Factions  --- Alternate route: &#x60;/latest/universe/names/&#x60;  Alternate route: &#x60;/v3/universe/names/&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postUniverseNamesTest() throws Exception {
        List<Integer> body = null;
        String datasource = null;
        List<PostUniverseNames200Ok> response = api.postUniverseNames(body, datasource);

        // TODO: test validations
    }
}
