/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.BadRequest;
import io.swagger.client.model.ErrorLimited;
import io.swagger.client.model.Forbidden;
import io.swagger.client.model.GatewayTimeout;
import io.swagger.client.model.InternalServerError;
import io.swagger.client.model.PostUiOpenwindowNewmailNewMail;
import io.swagger.client.model.PostUiOpenwindowNewmailUnprocessableEntity;
import io.swagger.client.model.ServiceUnavailable;
import io.swagger.client.model.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UserInterfaceApi
 */
@Ignore
public class UserInterfaceApiTest {

    private final UserInterfaceApi api = new UserInterfaceApi();

    /**
     * Set Autopilot Waypoint
     *
     * Set a solar system as autopilot waypoint  --- Alternate route: &#x60;/latest/ui/autopilot/waypoint/&#x60;  Alternate route: &#x60;/legacy/ui/autopilot/waypoint/&#x60;  Alternate route: &#x60;/v2/ui/autopilot/waypoint/&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postUiAutopilotWaypointTest() throws Exception {
        Boolean addToBeginning = null;
        Boolean clearOtherWaypoints = null;
        Long destinationId = null;
        String datasource = null;
        String token = null;
        api.postUiAutopilotWaypoint(addToBeginning, clearOtherWaypoints, destinationId, datasource, token);

        // TODO: test validations
    }
    /**
     * Open Contract Window
     *
     * Open the contract window inside the client  --- Alternate route: &#x60;/latest/ui/openwindow/contract/&#x60;  Alternate route: &#x60;/legacy/ui/openwindow/contract/&#x60;  Alternate route: &#x60;/v1/ui/openwindow/contract/&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postUiOpenwindowContractTest() throws Exception {
        Integer contractId = null;
        String datasource = null;
        String token = null;
        api.postUiOpenwindowContract(contractId, datasource, token);

        // TODO: test validations
    }
    /**
     * Open Information Window
     *
     * Open the information window for a character, corporation or alliance inside the client  --- Alternate route: &#x60;/latest/ui/openwindow/information/&#x60;  Alternate route: &#x60;/legacy/ui/openwindow/information/&#x60;  Alternate route: &#x60;/v1/ui/openwindow/information/&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postUiOpenwindowInformationTest() throws Exception {
        Integer targetId = null;
        String datasource = null;
        String token = null;
        api.postUiOpenwindowInformation(targetId, datasource, token);

        // TODO: test validations
    }
    /**
     * Open Market Details
     *
     * Open the market details window for a specific typeID inside the client  --- Alternate route: &#x60;/latest/ui/openwindow/marketdetails/&#x60;  Alternate route: &#x60;/legacy/ui/openwindow/marketdetails/&#x60;  Alternate route: &#x60;/v1/ui/openwindow/marketdetails/&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postUiOpenwindowMarketdetailsTest() throws Exception {
        Integer typeId = null;
        String datasource = null;
        String token = null;
        api.postUiOpenwindowMarketdetails(typeId, datasource, token);

        // TODO: test validations
    }
    /**
     * Open New Mail Window
     *
     * Open the New Mail window, according to settings from the request if applicable  --- Alternate route: &#x60;/latest/ui/openwindow/newmail/&#x60;  Alternate route: &#x60;/legacy/ui/openwindow/newmail/&#x60;  Alternate route: &#x60;/v1/ui/openwindow/newmail/&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postUiOpenwindowNewmailTest() throws Exception {
        PostUiOpenwindowNewmailNewMail body = null;
        String datasource = null;
        String token = null;
        api.postUiOpenwindowNewmail(body, datasource, token);

        // TODO: test validations
    }
}
